Infineon/XMC-for-Arduino

arm/cores/Tone.cpp
arm/cores/wiring_time.c
arm/cores/wiring_time.h

In the previous verisions micros() only had a resolution of 1ms. This
should be fixed with this update.
Refer to #16.

FIXED micros() Bug

---

arm/cores/HardwareSerial.cpp
arm/cores/HardwareSerial.h
arm/cores/RingBuffer.cpp
arm/cores/Tone.cpp
arm/cores/wiring_analog.c
arm/cores/wiring_constants.h
arm/cores/wiring_digital.c
arm/cores/wiring_digital.h
arm/cores/xmc_lib/XMCLib/inc/xmc_eth_mac.h
arm/cores/xmc_lib/XMCLib/inc/xmc_sdmmc.h
arm/cores/xmc_lib/XMCLib/inc/xmc_usbh.h
arm/cores/xmc_lib/XMCLib/src/xmc_eth_mac.c
arm/cores/xmc_lib/XMCLib/src/xmc_sdmmc.c
arm/cores/xmc_lib/XMCLib/src/xmc_usbh.c
arm/variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h
arm/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h
arm/variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h
arm/variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h
arm/variants/XMC4800/config/XMC4800_Relax_Kit/pins_arduino.h

Issue #26 
First stage of multi stage commits -
First part removes redefine true/false,
Second part removes bad inlining to reduce to standard functions (compiler ignores inlining anyway)

Reduce compiler warnings

---

arm/cores/wiring_time.c
arm/cores/wiring_time.h
arm/cores/xmc_lib/XMCLib/inc/xmc_vadc.h
arm/cores/xmc_lib/XMCLib/src/xmc_vadc.c

This fixes compiler warnings  for XMC1xxx and only leaves USB compiler warnings for XMC4xxxx 
Removes wasteful functions inlines simple millis() and micros() to reduce overhead
Simplifies and makes more readable many functions
XMC_SYSTIMER_lTimerHandler function has simplification to reduce size and adds methods of callback
```
*
* Special cases for callback action processing
*      args is NULL means a function with VOID parameter list called e.g function()
*      callback is NULL boolean delay_timer_expired is set to true
*
```
Reduces unnecessary callback
Makes flags used in handlers volatile to avoid issues

Final compiler warnings fix

---

arm/cores/xmc_lib/XMCLib/inc/xmc_device.h
arm/cores/xmc_lib/XMCLib/inc/xmc_sdmmc.h
arm/cores/xmc_lib/XMCLib/inc/xmc_usbh.h
arm/cores/xmc_lib/XMCLib/inc/xmc_vadc.h
arm/cores/xmc_lib/XMCLib/src/xmc_sdmmc.c
arm/cores/xmc_lib/XMCLib/src/xmc_usbh.c
arm/cores/xmc_lib/XMCLib/src/xmc_vadc.c
arm/variants/XMC1100/linker_script.ld
arm/variants/XMC1300/linker_script.ld
arm/variants/XMC4700/linker_script.ld
arm/variants/XMC4800/linker_script.ld

Enhancement  -Add  two new defines to xmc_defines.h on per family or series or chip , which creates defines to report in kB for 
UC_RAM programme memory only
UC_ALL_RAM Program and Special meory combined
Tidy ups on linker scripts for spelling mistakes and fuller filenames
XMC1 series reduce RAM wastage and move Stack to less dangerous are to avoid overruns
Reduce compiler warnings still exist compiler warnings in new version of XMCLIB a method of fixing is included as separate committ

Xmclib 2.1.6 changes to reduce compiler warnings and Enhancement

---

arm/cores/Tone.cpp
arm/cores/Tone.h
arm/cores/wiring_time.c
arm/cores/wiring_time.h
arm/cores/xmc_lib/XMCLib/inc/xmc_device.h
arm/platform.txt

Series of commits that
1. Correct Flash total to closer value after compile message
2. Gives A RAM estimate after compile that is at least 16 bytes short due to memory holes not counted, includes all sections even stack which could be 1024 or 2048 bytes depending on XMCLIB version.
3. Rewritten Systick 1ms timer event scheduler that has been tested on 4 Tones and delay (ms) uses hard coded arrays for schedule list and proven methods for scheduling co-operatively, approximate timings is from 5 micro seconds to execute when no tasks waiting and around 20 micro seconds when 5 tasks to be processed. This is on XMC1100. Allows for 4 tones on XMC1 series and 16 on XMC4 series.
Tone had to be modified to use the new scheduler.
Example 4 tones using on board LEDs available on request
4. Add …

Updates for Tone/wiring_time adding RAM totals to compile

---

arm/libraries/SPI/src/HW_SPI.cpp
arm/libraries/Wire/src/Wire.cpp

gcc version 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496] (GNU Tools for ARM Embedded Processors)  (downloaded from https://github.com/Infineon/Assets/releases/tag/current)
Without this fix, compiling this code 
```
#include <Arduino.h>
#include <Wire.h>
void setup()
{
}
void loop()
{
}
```
Ends with following error
```
Processing xmc1100_xmc2go (platform: infineonxmc; board: xmc1100_xmc2go; framework: arduino)
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
PLATFORM: Infineon XMC > XMC1100 XMC2Go
SYSTEM: 32MHz 64KB RAM (64KB Flash)
Library Dependency Finder -> …
```

Fix build when i2c is enabled.

---

arm/cores/WString.h

The move assignment operator is defined in the header, but not implemented in the .cpp
This can cause strange linker errors.
Signed-off-by: Peter Huewe <peter.huewe@infineon.com>

Remove not-implemented move assignment operator

---

arm/libraries/IFX9201/examples/MotorControl/MotorControl.ino
arm/libraries/IFX9201/src/IFX9201.cpp
arm/variants/XMC1100/config/XMC1100_H_BRIDGE2GO/pins_arduino.h

Pins of PWM and DIS were swapped (also wrong labels on PCB):
PWM is on P2.10 = Arduino Pin 11
DIS is on P2.11 = Arduino Pin 10
Fixes to mapping_pin_PWM4:
- Pin 8 was mapped to non-existing index 10 -> changed to index 0
- Added entry for Pin 11 (PWM of H-Bridge) -> mapped to index 1

Fixes to H-Bridge2Go Implementation

---

arm/cores/wiring_analog.c
arm/cores/wiring_analog.h
arm/variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h
arm/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h
arm/variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h

XMC2GO pin 0 and pin 1 were swapped compared to other documentation
Analog functions for init and read improved
PWM prescaler bug in CCU8 gave wrong prescaler
Add more safety, code reduction and documentation

Fixes to XMC2GO pinout, analog functions and PWM

---

.travis.yml

As motor control examples names changed update Travis automated tests to call correct example files when enabled

Travis administrative update

---

arm/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h

This commit adds 2 more analog ports and 3 more pwm ports to the
xmc2go variant. This is done by sharing existing ports, as already
done by xmc4700 relax and xmc1100 boot kit variants.
Also, ports A0 and A1 were swapped for a more intuitive port naming
scheme.
Changes:
Pin 1 -> MISO and PWM
Pin 2 -> SCK and PWM
Pin 3 -> SS and PWM
Pin 10 -> SCL and analog (A3)
Pin 11 -> SDA and analog (A2)
Pin 12 -> analog (A1)
Pin 13 -> analog (A0)

xmc2go: Add more analog and PWM ports

---

arm/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h

This commit swaps MISO and MOSI to keep compatibility with Shield2Go
layout.
While pin 0 and pin 1 were swapped previously (https://github.com/Infineon/XMC-for-Arduino/commit/0cacb835822d0b32779c1e7a74961a93d55e09d3),
MISO and MOSI pins were never swapped to keep compatibility with
existing hardware.
This commit follows XMC H-Bridge 2Go pin layout file: https://github.com/Infineon/XMC-for-Arduino/blob/37be6555e8c69921ff91253ec965c73cbc399535/arm/variants/XMC1100/config/XMC1100_H_BRIDGE2GO/pins_arduino.h#L72
Correct layout example: https://www.infineon.com/export/sites/default/_images/product/evaluation-boards/DPS310-Pressure-Shield2Go_Top_web.png_2070606871.png

xmc2go: Swap MISO and MOSI pins

---

arm/variants/XMC4700/startup_XMC4700.S
arm/variants/XMC4800/startup_XMC4800.S

Both xmc4700 and xmc4800 are Cortex-M4 based microcontrollers, as
so, both have ARMv7E-M instruction sets.
This commit silences the following warning:
"IT blocks containing more than one conditional instruction are
deprecated in ARMv8"
As my xmc4700 relax kit didn't arrive yet, I wasn't able to test it on real hardware.
I would be really grateful if someone tested it before merge.
Also, I was in doubt if the file version should be changed. Is it okay like that?

XMC4X00: Silence compiler warning by exposing correct arch

---

arm/boards.txt
arm/variants/XMC4700/config/XMC4700_Radar_Baseboard/pins_arduino.h

Commenting bug on NUM_ANALOG_INPUTS
NUM_PWM did not match list of PWMs assigned
Wrong compiler flags that was resolved September 2019 for similar XMC4700 Relax kit
causes redefinition of constants in other modules
Other potential bug exists in
~~~
const XMC_PIN_INTERRUPT_t mapping_interrupt[] =
~~~
Where this board has 6 entries per row ALL other boards use 5 per row
No time at present to chase this down, I suggest original author @mohamemu  check this

Fix simple Bugs in Radar XMC4700

---

arm/variants/XMC1400/config/XMC1400_Boot_Kit/pins_arduino.h
arm/variants/XMC4700/config/XMC4700_Radar_Baseboard/pins_arduino.h
arm/variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h
arm/variants/XMC4800/config/XMC4800_Relax_Kit/pins_arduino.h

These boards had their PCLK set to a wrong value, causing the function
"setAnalogWriteFrequency" to misbehave.
An example can be seen in the image below, where a frequency of 50hz was set
on a XMC4700 Relax board:
- Previous: https://i.imgur.com/9vfwv1d.jpg
- After: https://i.imgur.com/YGaZxsM.jpg
PCLK values were taken from the datasheets of each MCU. For XMC1400, the PCLK
also matches the one set by its initialization/startup rotine.

Config: Set correct PCLK values

---

libraries/Wire/src/utility/xmc_i2c_conf.c

Protocol IRQ number in Line 229 inside xmc_i2c_conf.c was 91 in place of 92.

Updating XMC4400 Wire Protocol Interrupt number form 91 to 92

---

cores/wiring_analog.c
cores/wiring_analog.h
keywords.txt

Add extra keywords for wiring_analog functions
Minor tidy up reduce variable count by 1
Assist use of functions

Add extra keywords wirining_analog and minor tidy

---

variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h

- when compiling with -DSERIAL_ONBOARD the define SERIAL_DEBUG becomes undefined.
This leads to the use of P1_2 as inputsource of USIC0_CH1. The corresponding define
specifies USIC0_C0_DX0_P1_2 which does not exist for XMC1100. Therefore
the define has been changed to the correct CH1 define USIC0_C1_DX0_P1_2.

Fix typo specifying wrong input source for XMC1100 BootKit USIC

---

package/package_infineon_index.template.json

Description
Updating the ARM gcc compiler to the latest version available on the ARM website. Part of internal ticket DESMakers-2494. 
Context
The current compiler 5.4.x is out-of-date and needs an update. The `package_infineon_index.template.json` file in the `package` folder is edited to use the latest version and also the upstream paths provided. The CI/CD workflow was used to test the new compiler outputs. 
More info in fork here: https://github.com/boramonideep/XMC-for-Arduino/tree/update_gcc
IMPORTANT NOTE: While releasing, the compiler binaries must be made part of release assets and the paths changed …

updated compiler to version 10.3-2021.10

---

cores/wiring_analog.c
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h

Description
Issues with duplicate pin assignments and wrong PWM4/8 mappings
Related Issue
Issue #185 
Context
- Certain pins were assigned more than once (in the X1 and X2 headers). Parallel operation of these pins for different functions can lead to unpredictable behavior. 
- PWM4 and PWM8 on certain pins were not working due to wrong mapping. 
Note: After removing the duplicate pin assignments, the pin numbers for the different peripherals have been changed.

Fix for Issue #185

---

variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h

Description
As per the user manual of the XMC1100 Boot Kit, pins 10 and 11 should be PWM outputs, in addition to being SPI pins. The PWM functionality was missing and has been added. 
Related Issue
None
Context
The PWM signals were tested and also the SPI functionality was tested with test programs.

PWM functionality on some pins of XMC1100 Boot Kit

---

variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Pin 14 on XMC4 series boards is a VAREF pin and hence cannot be used as a GPIO.
Related Issue
Issue #199 
Context
In order to prevent old legacy code from breaking, the pin assignments have been kept the same by use of dummy assignments (floating pins on MCU). This is planned to be finally fixed in the upcoming version 2.x

Fix for issue 199 for version 1.x

---

variants/XMC1400/config/XMC1400_Arduino_Kit/pins_arduino.h

Description
Enable PWM on pins 10 and 11 of XMC1400 Kit for Arduino 
Context
To make the BSP compatible with the User Manual, PWM must be enabled on pins 10 and 11, as shown below.

added PWM to pins 10 and 11 of XMC1400 Arduino Kit as per user manual

---

.github/workflows/compile-platform-examples.yml
README.md
boards.txt
libraries/SPI/src/utility/xmc_spi_conf.c
libraries/SPI/src/utility/xmc_spi_conf.h
libraries/Wire/src/utility/xmc_i2c_conf.c
libraries/Wire/src/utility/xmc_i2c_conf.h
package.json
package/package_infineon_index.template.json
variants/XMC1300/XMC1000_RomFunctionTable.h
variants/XMC1300/XMC1300.h
variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h
variants/XMC1300/linker_script_128k.ld
variants/XMC1300/linker_script_200k.ld
variants/XMC1300/linker_script_32k.ld
variants/XMC1300/linker_script_64k.ld
variants/XMC1300/startup_XMC1300.S
variants/XMC1300/system_XMC1300.c
variants/XMC1300/system_XMC1300.h

Description
Added XMC1300 Boot Kit support in 2.x

Added XMC1300 Boot Kit support in 2.x

---

libraries/BGT24LTR11-Pulsed-Doppler-Radar/README.md
libraries/BGT24LTR11-Pulsed-Doppler-Radar/examples/RadarPulsedDoppler_Andee_RGB/RadarPulsedDoppler_Andee_RGB.ino
libraries/SPI/src/utility/xmc_spi_conf.c
libraries/SPI/src/utility/xmc_spi_conf.h
libraries/Wire/src/utility/xmc_i2c_conf.c
libraries/Wire/src/utility/xmc_i2c_conf.h

Description
XMC4700 Radar baseboard was missing in the SPI & I2C config files. Due to this in the example, Radar_pulsed_Doppler_Andee_RGB was showing errors. It's fixed by this pull request.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.

updated I2C & SPI config with radar base board

---

README.md

Description
When using pins connected to LEDs as INPUTs, there is a bias voltage created due to the series resistor of the LED. This interferes with the GPIO behavior. 
This PR adds a warning in the README for the user.

added section to README about the LED pin as input issue

---

boards.txt

Description
Certain mistakes in boards.txt
Context
- Information in boards.txt file is verified.
- Mistakes found and corrected, similar to V2.x
- Serial communication via PC was not working before on HBRIDGE2Go due to a wrong compile-time define. Corrected
Testing
- No testing required for the changes similar to V2.x since the change was only in the package number of the XMC1100 in XMC2Go is changed. This would only change the define macros for the particular device type. There are no differences in those except for the pins that do not occur …

Changes to boards.txt for V1.7

---

libraries/LED/Readme.md
libraries/LED/library.properties
libraries/LED/src/LED.cpp
variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h

Description
On XMC1300 Boot Kit the LED_Builtin is reversed to normal Arduino standard. On all other boards LED_BUILTIN works as per Arduino standard, but maybe different to XMC_LED_ON setting, this corrects both situations.
This V2.x version of previous PR for develop1.x for LED library

V2.x LED Library reversed LED_BUILTIN

---

libraries/LED/Readme.md
libraries/LED/library.properties
libraries/LED/src/LED.cpp
variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h
variants/XMC1300/config/XMC1300_Sense2GoL/pins_arduino.h

Description
On XMC1300 boards (Boot Kit and Sense2GO) The LED_BUILTIN is reversed to normal Arduino standard. On all other boards LED_BUILTIN works as per Arduino standard, but maybe different to XMC_LED_ON setting, this corrects both situations. Provides UNIFORM calls for LED being turned on or off across all boards and all LEDs on each board
See LED Library Readme.md for table of known variations
Related Issue
N/A
Context
This will also work on develop branch (for V2.x)

LED Library reversed LED_BUILTIN

---

variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h

Description
Add PWM channel 
Context
Enable PWM output on A3 to make it compatible to Arduino Uno. Certain motor control shields work on Arduino Uno but not on XMC1100 BootKit.

added changes to enable PWM channel in XMC1100 Boot Kit

---

cores/HardwareSerial.cpp
libraries/SPI/src/HW_SPI.cpp
libraries/Wire/src/Wire.cpp

Put the GPIO_Init() after CH_Start for SPI, I2C and HardwareSerial in order to avoid false pulses as described in issue #234 
Description
With this PR the GPIO_Init() functions are moved after XMC_CH_Start() of I2C, SPI and HardwareSerial.
This solves the issue #234 with wrong pulses output on the communication lines.
Also in the respective end() functions
Related Issue
#234

GPIO Init after USIC CH Start

---

libraries/Wire/src/Wire.cpp

Description
Added wait in I2C transaction
Context
Added a wait state until ACK is received after sending a START or REP_START. This was absent before so it leads to a intermittent erroneous reading from I2C sensors.

added wait for ACK after a I2C transaction

---

cores/avr/dtostrf.c
cores/avr/dtostrf.h

**Description**
Implementation of `dtostrf()` was based on `sprintf()`, which is not implemented for floats/doubles in Arduino according to [1].
This PR replaces `dtostrf()` implementation by one which is not based on `sprintf()` (reference is stdlib_noniso.h by Ivan Grokhotkov under GNU LGPL).
**Context**
Tested with XMC for Arduino 3.0 and XMC1100 2Go board.
[1] https://forum.arduino.cc/t/sprintf-with-float-values/937562

fix implementation of dtostrf

---

.github/workflows/compile-platform-examples.yml
.gitignore
libraries/CAN/Makefile
libraries/CAN/Makefile.test
libraries/CAN/README_CAN.md
libraries/CAN/examples/CANReceiver/CANReceiver.ino
libraries/CAN/examples/CANReceiverCallback/CANReceiverCallback.ino
libraries/CAN/examples/CANSender/CANSender.ino
libraries/CAN/src/CAN.h
libraries/CAN/src/CANXMC.cpp
libraries/CAN/src/CANXMC.h
libraries/CAN/test/unit/Unity/unity.c
libraries/CAN/test/unit/Unity/unity.h
libraries/CAN/test/unit/Unity/unity_config.h
libraries/CAN/test/unit/Unity/unity_fixture.c
libraries/CAN/test/unit/Unity/unity_fixture.h
libraries/CAN/test/unit/Unity/unity_fixture_internals.h
libraries/CAN/test/unit/Unity/unity_ifx.h
libraries/CAN/test/unit/Unity/unity_internals.h
libraries/CAN/test/unit/Unity/unity_memory.c
libraries/CAN/test/unit/Unity/unity_memory.h
libraries/CAN/test/unit/src/framework/arduino/Test_CAN.cpp
libraries/CAN/test/unit/src/framework/arduino/Test_CAN_connected.cpp
libraries/CAN/test/unit/src/framework/arduino/Test_includes.hpp
libraries/CAN/test/unit/src/framework/arduino/Test_main.ino
libraries/CAN/test/unit/src/framework/arduino/unity_ifx.cpp

Description
Enable all CAN basic function s
Related Issue
n/a
Context
https://jirard.intra.infineon.com/browse/DESMAKERS-3775 (CAN API)
https://jirard.intra.infineon.com/browse/DESMAKERS-3821 (Unity Test) - Sorry again I will try to separate the PR next time... 🐱 
The XMC CAN module works a bit different: It will not receive all data frames and then filter them. Instead, it only accept data frame with defined ID/ ID Mask. Spent two days reading the user manual and experimenting, no success
⚠️ Therefore the extra setDeviceId() function is added …

XMC CAN Sending & Unity starting point 

---

tools/xmc_data.py

Description
XMC for Arduino do not work with XMC1300 Boot Kit (which uses XMC130**2** Microcontroller). Uploading sketch ends up with following error with curious description:
```
Traceback (most recent call last):
File "C:\Users\michal\AppData\Local\Arduino15\packages\Infineon\hardware\xmc\3.0.0/tools/xmc-flasher.py", line 263, in <module>
parser()
File "C:\Users\michal\AppData\Local\Arduino15\packages\Infineon\hardware\xmc\3.0.0/tools/xmc-flasher.py", line 258, in parser
args.func(args) 
File …
```

Fix wrong XMC1300 Boot Kit identifier in xmc_data.py

---

variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Pin 75 is connected with P5.3 which is set also to pin 79, therefore pin 75 does not work at all.
Related Issue
Relocate pin 75 on the XMC4700 from P5.3 to P6.3, possible typo.

Exchange P5.3 with P6.3 on pin 75

---

cores/Arduino.h
libraries/CAN/README_CAN.md
libraries/CAN/examples/CANReceiver/CANReceiver.ino
libraries/CAN/examples/CANReceiverCallback/CANReceiverCallback.ino
libraries/CAN/examples/CANSender/CANSender.ino
libraries/CAN/src/CANXMC.cpp
variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h
variants/XMC4200/config/XMC4200_Platform2GO/pins_arduino.h
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Now sendpacket() support both 11 & 29 bits identifier. same for receive. 
Functions that are not the same as the official API can be removed, updating the README and example sketches.
Related Issue
N/A
Context
Once it's up and running, it works ;)

DESMAKERS-3827: enable 11/29Bits id frame send and receive

---

libraries/CAN/README_CAN.md
libraries/CAN/src/CANXMC.cpp
variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h
variants/XMC4200/config/XMC4200_Platform2GO/pins_arduino.h
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Update: README regarding filtering issue
Description
Implement the Filtering API
Related Issue
NA
Context
Packets of information can be filtered based on id/ mask. 
⚠️ So far xmc4x and xmc1x have different behaviors -> Need further examination but currently focusing on xmc1400 2go

Add: Filtering API

---

libraries/CAN/README_CAN.md
libraries/CAN/examples/CANReceiverCallback/CANReceiverCallback.ino
libraries/CAN/examples/CANSender/CANSender.ino
libraries/CAN/src/CANXMC.cpp
libraries/CAN/src/CANXMC.h

Description
remove namespace ifx
Related Issue
NA
Context
As discussed, no namespace for BSP

Fix: remove namespace ifx

---

platform.txt
tools/xmc-flasher.py
tools/xmc_data.py

Description
Improve xmc flasher
Related Issue
DESMAKERS3766, DESMAKERS4040
Context
- If no serial port is selected, pick first jlink device and log the right port 
- Remove mojibake in uploading log
:no_entry: Synchronizing uploading windows of arduino IDE and the flasher script log as much as possible -> This delay also occurs when using arduino cli. It cannot be improved unless the arduino source code is changed

Fix: automatically select default port and remove mojibake

---

tools/xmc-flasher.py

Description
Error when flash in Linux. Adapt Regex expression
Thanks Olaf for finding this bug and providing a workaround
Related Issue
JLink device name is different for different OS.
Context
Tested on all OS

Fix: Cannot find JLink device in Linux 

---

cores/HardwareSerial.cpp

Description
The if condition to store data in the buffer is triggered regardless of the current uart transmit status if tail and head differ:
```
if(( XMC_USIC_CH_GetTransmitBufferStatus( _XMC_UART_config->channel ) == XMC_USIC_CH_TBUF_STATUS_BUSY )
|| ( _tx_buffer->_iTail != _tx_buffer->_iHead ))
```
This can lead to an infinte loop in the spinlook if the transmit IRQ is executed in the wrong moment and not new transmission is started. To prevent this a check is added to ensure that a new transmission is started if non is currently in progress …

Fixed edge case that might lead to Serial beeing stuck in spinlook wait

---

.github/workflows/hil-unity-checks.yml
tests/Unity/Makefile
tests/Unity/hil-unity-checklist.yaml

Description
This PR includes:
- HIL setup for unity tests including compile and flash on multiple devices with interconnection of devices
- generic GH action yaml
- including yaml file for controlling available unity tests
- reporting of console output for single and multiple devices
- collecting of builds and reports for downloading as artifact
- cleanup and extension of the main make file
Context
This HIL setup runs on Infineon self hosted runner with certain devices and interconnected devices for testing XMC-for-Arduino software
Commits will be squashed.

Desmakers 3803 new hil setup

---

libraries/Wire/src/Wire.cpp

Error: Wire.cpp got stocked in the while-loop for the timeout since the timeout-condition was not defined as it should be per definition. It was not possible to leave the while-loop after the timeout-variable reached 0.
Change: Now, the checking condition was reduced to the essentials (it was wrong before) and another if-condition, which checks if the timeout-variable reached 0, was added inside the while-loop. This leads to a break.
Testing: The new wire.cpp was tested with the KIT_XMC_2GO_XMC1100_V1 & KIT_XMC47_RELAX_LITE_V1. Both worked.

Adapting timeout while-loop in Wire.cpp

---

cores/HardwareSerial.cpp

Description
Removed the transmit ringbuffer in order to quickly fix this Serial.print().
More changes will be made when replace coreAPI.
Related Issue
Please check DESMAKERS 4270
Context
For UART transmission, the original XMC4Arduino implementation was very confusing. Although our XMC USIC already comes with a hardware buffer and the xmclib API has a wait feature to block tx, we also use an additional software Ringbuffer. So We remove the ringbuffer and simply use the XMC_UART_CH_Transmit API (When FIFO is not configured, the API waits for the …

Bugfix/desmakers 4270 serial.print is not allways working correctly in xmc for arduino version 3.5.0

---

.github/workflows/compile-platform-examples.yml

Description
Compilation test is not running due to deprecation of upload-artifact.
Related Issue
https://github.com/actions/upload-artifact/issues/478
It seems that upload-artifacts v4 does not allow all outputs in the build matrix to be uploaded to one folder. 
So now artifact is uploaded under different board names.
Context

CI: Update compile-platform-examples.yml

---

.github/workflows/compile-platform-examples.yml
package/package_infineon_index.template.json
tests/hil-unity-checklist.yaml

Description
rename the metafile vendor from infineon to infineon
Related Issue
Desmakers 4279
Context
Also need to adapt the documentation.
Will update the other PR.

Desmakers 4279 rename the metafile vendor from infineon to infineon

---

tools/ci.sh
tools/verifygitlog.py

Description
Running commit message checking for xmc4arduino.
Due to the history of commit messages, we need to tweak the script and workflow a bit.
Related Issue
Context

Commit msg check modification

---

variants/XMC1400/config/XMC1400_Arduino_Kit/pins_arduino.h
variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h

**Description**
This pull request includes changes to the `pins_arduino.h` files for the `XMC1400_Arduino_Kit` and `XMC1400_XMC2GO` variants. The changes involve adding external variable declarations for SPI pin assignments.
* [`variants/XMC1400/config/XMC1400_Arduino_Kit/pins_arduino.h`](diffhunk://#diff-aa5e6a88ffc2c6c8bbacf26f182bf2d03e43768b38784badfe5d10aa6bd265d5R82-R86): Added external variable declarations for `SS`, `MOSI`, `MISO`, and `SCK` to define SPI pin assignments.
* [`variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h`](diffhu …

variants/XMC1400: Add SPI pin definitions.

---

cores/xmc/Arduino.h
cores/xmc/Uart.cpp
cores/xmc/Uart.h
cores/xmc/main.cpp
tests/test_config.h
variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h
variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h
variants/XMC1300/config/XMC1300_Boot_Kit/pins_arduino.h
variants/XMC1400/config/XMC1400_Arduino_Kit/pins_arduino.h
variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h
variants/XMC4200/config/XMC4200_Platform2GO/pins_arduino.h
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Serial module Implementation
Related Issue
Bug: https://jirard.intra.infineon.com/browse/DESMAKERS-4557
Context
Now only have ringbuffer for receiving, for sending, its write immediately. 
If you check the API description for XMC_UART_CH_Transmit(): _Before putting data to TBUF, the API waits for TBUF to finish shifting its contents to shift register. So user can continuously execute the API without checking for TBUF busy status_ We @OlafFilies had a discuss before.
Code is simple and understandable.

Core api update serial

---

cores/xmc/WInterrupts.c
tests/test_config.h

Description
Invalid pin and mode test cases not getting pass , so modified the code.
Context
tested with 4700 board.

Core api update interrupt changes

---

cores/xmc/Arduino.h
cores/xmc/Tone.cpp
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Tone function implemented using PWM method. In XMC we have two modes CCU4 and CCU8 . configured for all the PWM pins.
Related Issue
Removed delay in test_main.ino because test case not running in continuous loop. 
Context
Tested with 4700 Board, connected jumber wire in between interrupt pin and pwm pin.

Core api update tone

---

libraries/Wire/src/Wire.cpp
libraries/Wire/src/Wire.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h

Description
Implemented Ringbuffer, error handling in endTransmission() function.
Related Issue
Every 20 to 30 seconds getting one or two iteration fail during Master pingpong and slavepingpong test case running. Suspecting timeout mechanism.
Context
Tested with two XMC 4700 board which one is master and one is slave, used 4.7K ohm resistor 
and Tested with Mastersender  - slavereceiver and Master Receiver - Slave sender arduino examples this is also working.
this screenshot of single board pingpong test multiple wire pins

Core api update iic modify

---

libraries/Wire/src/Wire.cpp

Description
Regarding I2C scan not working in pervious version , here its fixed after added 1ms delay , actually its not stable so i got so many address, after added delay its resolved
Jira ticket: https://jirard.intra.infineon.com/browse/DESMAKERS-4423
Related Issue
I2C scan not worked pervious version and 4.0.0 not stable.
This image is not stable in 4.0.0
Context
Here tested with 4700 , connected 2 I2C slave, one is OLED and another one pressure sensor DPS422

libraries/Wire/src: Fixed iic scan bug.
