README.md
README.txt
arm/cores/HardwareSerial.cpp
arm/cores/HardwareSerial.h

Added check if serial available during serialEvent

---

arm/libraries/SPI/src/HW_SPI.cpp
arm/libraries/SPI/src/SW_SPI.cpp
arm/libraries/Wire/src/Wire.cpp
arm/libraries/Wire/src/Wire.h

Solves problem for xmc1100 boards that SPI and I2C can not be used at the same time

UPDATE for SPI and Wire Lib - shared USIC

---

arm/cores/wiring_time.c

CHANGED: implementation in wiring_time

Hotfix for wiring_time

---

arm/variants/XMC1100/config/XMC1100_XMC2GO/pins_arduino.h

Fixed Bug: Serial Rx XMC2GO

---

platform.txt

Arduino library and board specification URL has moved, update to current

Update Library Spec URL

---

libraries/DeviceControlXMC/examples/DieTemperatureMeasurement/DieTemperatureMeasurement.ino
libraries/DeviceControlXMC/examples/SleepModeXMC4700/SleepModeXMC4700.ino
libraries/DeviceControlXMC/src/DeviceControlXMC.cpp
libraries/DeviceControlXMC/src/DeviceControlXMC.h
libraries/RTC/src/RTC.cpp
libraries/RTC/src/RTC.h
libraries/RTC/src/utility/xmc_rtc_conf.c
libraries/RTC/src/utility/xmc_rtc_conf.h
tests/PCLKTest/PCLKTest.ino
tests/PWMtest/PWMtest.ino
tests/Servotest/Servotest.ino

Change DeviceControl to allow reporting of negative temperatures, examine functions for later move to core for reading temperature.
Tidy some DeviceControl for simpler compiling and maintenance
Add etra tests for Servo/PWM/PCLK testing to see if better accuracy can be achieved

Die temp read negative temp and tidies

---

boards.txt
variants/XMC1100/config/XMC1100_Boot_Kit/pins_arduino.h
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h
variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h
variants/XMC4800/config/XMC4800_Relax_Kit/pins_arduino.h

Updates and tidies pins_arduino.h for readability and show Common pins for I2c and A4/A5 also additional Analogue inputs for XMC1100 Boot kit

Develop Update I2C and ADC input common pins comments

---

.vscode/settings.json
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h

Description
The SERIAL_ONBOARD functionality wasn't functional due to a mismatch in the IRQ pointer and Service Request line provided in the configuration. This was fixed, part of the code refactored and unwanted parts removed. 
Related Issue
Issue #197 
Context
SERIAL_ONBOARD functionality tested along with SERIAL_HOSTPC (Debug), using a suitable program and valid outputs expected in console.

Fix for issue #197

---

README.md
package/package_infineon_index.template.json
platform.txt
variants/XMC4400/config/XMC4400_Platform2GO/pins_arduino.h

Description
Nomenclature changes and other fixes
To be merged to master and tagged and released as 2.0.0

develop into develop for 2.x changes

---

README.md

Added python installation requirements.

Add py install requirement

---

tools/xmc-flasher.py

Description
Fixing certain issues with the new XMC Flasher script

Fix xmc flasher

---

variants/XMC1400/config/XMC1400_XMC2GO/pins_arduino.h

Description
Add ERU-based button reset for XMC1400 2GO

added GPIO reset logic for XMC14002GO

---

tools/xmc-flasher.py

**Description**
Minor change: Move winreg importing to Windows-related function to avoid error in non-windows systems.
**Related Issue**
Issue #267

move winreg to avoid import error in non-windows systems

---

.github/workflows/stale_issues.yml

Add a workflow file for automatically closing stale issues.
Tested in github.com/Infineon/arduino-high-side-switch

add stale_issues workflow

---

.github/workflows/docs.yml
.github/workflows/pre-commit.yaml

Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.

Feature: Add pre-commit workflow and fix doc build

---

tests/Makefile.test
tests/hil-unity-checklist.yaml

Description
Add serial test and update submodule
Related Issue
NA
Context
Open topic:
Check on HIL

Desmakers 4171 prepare test infrastructure for serial module

---

.github/workflows/commit_formatting.yml
.pre-commit-config.yaml
tools/ci.sh
tools/dev-setup.sh
tools/verifygitlog.py

Description
Adding commit message formatter. Checking start from master latest commit message
Related Issue
Desmakers 4283
Context

Desmakers 4283 implement commit message format check

---

.gitignore

Description
Fix .gitignore
Related Issue
Context

./gitignore: Fix noise command.

---

cores/xmc/Pulse.cpp
cores/xmc/Shift.cpp
tests/test_config.h

Description
Implemented shift and pulse function.  
Related Issue
If possible, Need to change the timer method for pulse in and pulse long function. 
Context
Tested with 2 board , connect 2 wires one is feedback and one is pulse
ShiftOut

Core api update pulse shift

---

ci-matrix-config.yml
package/config.yml
package/package_infineon_index.template.json
package/package_xmc_index.template.json
platform.txt
tests/Makefile.test
tests/hil-unity-checklist.yaml

Description
update metafiles naming according the convention: https://confluencewikiprod.intra.infineon.com/spaces/ARDUINO/pages/1951456037/Metafiles+variables+naming+conventions
Related Issue
https://jirard.intra.infineon.com/browse/DESMAKERS-4121
Context
We need to discuss how to handle the board name.
But I think the “Infineon” “infineon” issue has to be fixed because it affects psoc...

4.0.0 metafiles naming conventions

---

README.md

This pull request adds a new tip section to the `README.md` file, encouraging users to participate in a survey about their preferred XMC™ boards. The survey aims to gather feedback to improve support for these boards. 
Documentation update:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R11-R14): Added a tip section with a link to a survey and a deadline for participation (August 31, 2025).

README.md: Add temporary survey link.

---

libraries/CAN/README.md

libraries/CAN/README.md: Revoved deprecated link.

---

cores/HardwareSerial.cpp

Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.

cores: Fix Serial.

---

docs/development-instructions.rst

This pull request updates the `docs/development-instructions.rst` file to improve clarity and provide additional guidance for environment setup.
Documentation update:
* Added a link to detailed Python installation instructions by including a reference to `:doc:`installation-instructions`` in the "Environment Setup" section. This ensures users have clear guidance on how to set up Python.By creating this pull request you agree to the terms in CONTRIBUTING.md.
Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If …

docs/: Add installation reference.

---

config/user.yml

Description
Fix timer test. Aligned with psoc and should also work on psoc.
Related Issue
https://github.com/Infineon/arduino-core-tests/pull/75
Context

  config/user.yml: Fix timer test.

---

config/project.yml
config/user.yml

Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.

config: Added SPI single test.

---

config/project.yml
config/user.yml

Description
Update makers-devops and change the config file according new makers-hil.
Add oneWire, CAN and new 1400 Arduino kit.
Related Issue
N/A
Context
Releted to MR in makers-hil.

Update makers-devops and hil config
